<?php 

/**
 * Implementation of hook_menu().
 */
function wysiwyg_ckeditor_imageupload_menu() {

	$items = array();

	$items['admin/config/content/wysiwyg/ckeditor_imageupload'] = array(
		'title' => 'File upload',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('wysiwyg_ckeditor_imageupload_config_form'),
		'access arguments' => array('access administration pages'),
		'file' => 'wysiwyg_ckeditor_imageupload_config_form.inc',
		'type' => MENU_CALLBACK,
		);

	$items['wysiwyg/ckeditor/imageupload'] = array(
		'title' => 'File upload',
		'page callback' => '_wysiwyg_ckeditor_imageupload',
		'page arguments' => array(),
		'access callback' => array("wysiwyg ckeditor imageupload"),
		'type' => MENU_CALLBACK,
		);

	return $items;
}


/**
 * Implementation of hook_permission().
 */
function wysiwyg_ckeditor_imageupload_permission() {
	return array('wysiwyg ckeditor imageupload' => array(
		'title' => t('Upload files with CKEditor'),
		'description' => t('Allow the upload of images using CKEditor.'),
		), );
}


/**
 * Implementation of hook_wysiwyg_editor_settings_alter().
 */
function wysiwyg_ckeditor_imageupload_wysiwyg_editor_settings_alter(&$settings, $context) {

	if($context["editor"]["name"] == "ckeditor") {
		if(variable_get('wysiwyg_ckeditor_imageupload_disable_advanced', FALSE)) {
			$settings['removeDialogTabs'] = 'image:advanced';
		}

		$settings['filebrowserUploadUrl'] = '/wysiwyg/ckeditor/imageupload';
	}
}


function _wysiwyg_ckeditor_imageupload() {

	$folder = "wysiwyg_ckeditor_imageupload/";
	$folderFullPath = drupal_realpath(file_default_scheme() . '://') . "/" . $folder;

	$callback = $_GET["CKEditorFuncNum"];
	$msg =  FALSE;
	$url =  FALSE;

	$tmpPath = $_FILES['upload']['tmp_name'];
	$filename = $_FILES['upload']['name'];
	$destPath = $folderFullPath . "/" . $filename;

  	// Validate the output folder
	if (!file_exists($folderFullPath)) {
		mkdir($folderFullPath, 0777, true);
	}

  	// Validate that file is image
	$imageData = @getimagesize($tmpPath);
	if($imageData === FALSE || !($imageData[2] == IMAGETYPE_GIF || $imageData[2] == IMAGETYPE_JPEG || $imageData[2] == IMAGETYPE_PNG)) {

		$msg = t("File is not a valid image.", array(), array("context"=>"wysiwyg_ckeditor_imageupload"));

	} else if(move_uploaded_file($tmpPath, $destPath)) {

		global $user;
		$uri = 'public://'.$folder.$filename;

		$file = new stdClass;
		$file->uid = $user->uid;
		$file->filename = $filename;
		$file->uri = $uri;
		$file->filemime = 'text/plain';
		$file->filesize = filesize($uri);
		$file->status = 1;

		file_save($file);

		$url =  file_create_url($file->uri);

	} else {

		$msg = t("Upload could not be completed.", array(), array("context"=>"wysiwyg_ckeditor_imageupload"));
	}

  	// Output
	print '<html><body><script type="text/javascript">';
	print 'window.parent.CKEDITOR.tools.callFunction('.$callback.', "'.$url.'","'.$msg.'");';
	print '</script>';
	print '</body></html>';

	exit;

}
