<?php

/**
 * Implementation of hook_block_info()
 */
function innocar_gmaps_block_info() {

  // This example comes from node.module.
  $blocks['innocar_gmaps'] = array(
    'info' => t('Contact map'), 
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;
}

/**
 * Implementation of hook_block_view()
 */
function innocar_gmaps_block_view($delta = '') {

  $gKey = "AIzaSyADzqV8w2HT66LWjpDd0c1KH6jp_9nQKZI";
  $modulePath = drupal_get_path('module', 'innocar_gmaps');

  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
    case 'innocar_gmaps':

      drupal_add_js($modulePath . "/innocar_gmaps.js");
      drupal_add_js("https://maps.googleapis.com/maps/api/js?sensor=false&key={$gKey}", 'external');

      $block['subject'] = t('Contact map');
      $block['content'] = array(
        '#markup' => '<div id="innocar_gmaps" style="width:100%;height:470px;"></div><script>jQuery.fn.innocar_gmaps()</script>', 
        '#title' => t('Contact map'),
      );
      break;
  }
  return $block;
}

?>
